/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_whaty_penserver_utils_SoundResourceDecoder */
#include "jnicommon.h"

#ifndef _Included_com_whatyplugin_imooc_logic_proxy_MCResourceDecoderNative
#define _Included_com_whatyplugin_imooc_logic_proxy_MCResourceDecoderNative
//这里添加个  #ifdef NDK_BUILD 方便调试用
#ifdef NDK_BUILD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whaty_penserver_utils_SoundResourceDecoder
 * Method:    getMp3PathByCode
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_whatyplugin_imooc_logic_proxy_MCResourceDecoderNative_encode
  (JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_com_whatyplugin_imooc_logic_proxy_MCResourceDecoderNative_decode
	(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
#endif
